---

- name: grafana-configure | Compile Nginx configuration
  template: src=nginx.conf.j2 dest={{nginx_dir|default('/etc/nginx')}}/sites-enabled/grafana.conf
  when: grafana_nginx
  notify:  nginx reload 
