---

- name: Grafana setup | deploy stack
  shell: >
    docker swarm init |true ;
    docker stack deploy -c /etc/grafana/docker-compose.yml dash;
  tags: grafana-deploy

- name: Grafana setup | update stack
  shell: >
    docker service update dash_grafana;
  tags: deploy
